from __future__ import annotations

import json
import uuid
from contextlib import contextmanager
from typing import Any, Iterator

from .models import ProofObligation, ScientificNode

try:  # pragma: no cover - exercised only when optional dependency is installed
    import psycopg
    from psycopg.rows import dict_row
except ModuleNotFoundError:  # pragma: no cover
    psycopg = None  # type: ignore[assignment]
    dict_row = None  # type: ignore[assignment]


POSTGRES_SCHEMA = """
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS nodes (
    id TEXT PRIMARY KEY,
    kind TEXT NOT NULL,
    title TEXT NOT NULL,
    domain TEXT NOT NULL,
    summary TEXT NOT NULL,
    mechanism TEXT NOT NULL,
    math_structure TEXT NOT NULL,
    problem_shape TEXT NOT NULL,
    failure_modes TEXT NOT NULL DEFAULT '',
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS edges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id TEXT NOT NULL REFERENCES nodes(id),
    target_id TEXT NOT NULL REFERENCES nodes(id),
    relation TEXT NOT NULL,
    weight DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    evidence_json JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS vectors (
    node_id TEXT NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,
    axis TEXT NOT NULL,
    vector vector NOT NULL,
    canonical_text TEXT NOT NULL DEFAULT '',
    provider TEXT NOT NULL DEFAULT 'unknown',
    model TEXT NOT NULL DEFAULT 'unknown',
    dimensions INTEGER NOT NULL DEFAULT 0,
    content_hash TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (node_id, axis)
);

CREATE TABLE IF NOT EXISTS discovery_runs (
    id TEXT PRIMARY KEY,
    problem_id TEXT NOT NULL REFERENCES nodes(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    trace_json JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS hypotheses (
    id TEXT PRIMARY KEY,
    run_id TEXT NOT NULL REFERENCES discovery_runs(id) ON DELETE CASCADE,
    problem_id TEXT NOT NULL REFERENCES nodes(id),
    analogy_node_id TEXT NOT NULL REFERENCES nodes(id),
    title TEXT NOT NULL,
    bridge TEXT NOT NULL,
    prediction TEXT NOT NULL,
    rationale TEXT NOT NULL,
    status TEXT NOT NULL,
    critic_score DOUBLE PRECISION NOT NULL,
    failure_reason TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS proof_obligations (
    id TEXT PRIMARY KEY,
    hypothesis_id TEXT NOT NULL REFERENCES hypotheses(id) ON DELETE CASCADE,
    position INTEGER NOT NULL,
    statement TEXT NOT NULL,
    status TEXT NOT NULL,
    verification_method TEXT NOT NULL,
    notes TEXT NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS nodes_kind_idx ON nodes(kind);
CREATE INDEX IF NOT EXISTS vectors_axis_idx ON vectors(axis);
"""


def _require_psycopg() -> None:
    if psycopg is None:
        raise RuntimeError(
            "Postgres support requires the optional dependency: "
            "pip install 'science-researcher[postgres]'"
        )


def _vector_literal(vector: list[float]) -> str:
    return "[" + ",".join(f"{value:.12g}" for value in vector) + "]"


def _parse_vector(value: Any) -> list[float]:
    if isinstance(value, list):
        return [float(item) for item in value]
    text = str(value).strip()
    if text.startswith("[") and text.endswith("]"):
        text = text[1:-1]
    if not text:
        return []
    return [float(item) for item in text.split(",")]


class PostgresGraphStore:
    """GraphStore-compatible storage backed by Postgres and pgvector.

    Neon is just managed Postgres, so this class intentionally avoids Neon-only
    APIs. Any Postgres database with the `vector` extension should work.
    """

    def __init__(self, database_url: str) -> None:
        if not database_url:
            raise ValueError("database_url must not be empty")
        self.database_url = database_url

    @contextmanager
    def connect(self) -> Iterator[Any]:
        _require_psycopg()
        assert psycopg is not None
        assert dict_row is not None
        connection = psycopg.connect(self.database_url, row_factory=dict_row)
        try:
            yield connection
            connection.commit()
        finally:
            connection.close()

    def initialize(self) -> None:
        with self.connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute(POSTGRES_SCHEMA)

    def upsert_node(self, node: ScientificNode) -> None:
        with self.connect() as connection:
            connection.execute(
                """
                INSERT INTO nodes (
                    id, kind, title, domain, summary, mechanism,
                    math_structure, problem_shape, failure_modes, metadata_json
                ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s::jsonb)
                ON CONFLICT(id) DO UPDATE SET
                    kind=excluded.kind,
                    title=excluded.title,
                    domain=excluded.domain,
                    summary=excluded.summary,
                    mechanism=excluded.mechanism,
                    math_structure=excluded.math_structure,
                    problem_shape=excluded.problem_shape,
                    failure_modes=excluded.failure_modes,
                    metadata_json=excluded.metadata_json
                """,
                (
                    node.id,
                    node.kind,
                    node.title,
                    node.domain,
                    node.summary,
                    node.mechanism,
                    node.math_structure,
                    node.problem_shape,
                    node.failure_modes,
                    json.dumps(node.metadata, sort_keys=True),
                ),
            )

    def get_node(self, node_id: str) -> ScientificNode:
        with self.connect() as connection:
            row = connection.execute("SELECT * FROM nodes WHERE id = %s", (node_id,)).fetchone()
        if row is None:
            raise KeyError(node_id)
        metadata = row["metadata_json"]
        if isinstance(metadata, str):
            metadata = json.loads(metadata)
        return ScientificNode(
            id=row["id"],
            kind=row["kind"],
            title=row["title"],
            domain=row["domain"],
            summary=row["summary"],
            mechanism=row["mechanism"],
            math_structure=row["math_structure"],
            problem_shape=row["problem_shape"],
            failure_modes=row["failure_modes"],
            metadata=dict(metadata),
        )

    def list_nodes(self, *, kind: str | None = None) -> list[ScientificNode]:
        query = "SELECT id FROM nodes"
        params: tuple[Any, ...] = ()
        if kind is not None:
            query += " WHERE kind = %s"
            params = (kind,)
        query += " ORDER BY id"
        with self.connect() as connection:
            ids = [row["id"] for row in connection.execute(query, params).fetchall()]
        return [self.get_node(node_id) for node_id in ids]

    def put_vector(self, node_id: str, axis: str, vector: list[float]) -> None:
        with self.connect() as connection:
            connection.execute(
                """
                INSERT INTO vectors (node_id, axis, vector, dimensions)
                VALUES (%s, %s, %s::vector, %s)
                ON CONFLICT(node_id, axis) DO UPDATE SET
                    vector=excluded.vector,
                    dimensions=excluded.dimensions,
                    created_at=now()
                """,
                (node_id, axis, _vector_literal(vector), len(vector)),
            )

    def get_vector(self, node_id: str, axis: str) -> list[float]:
        with self.connect() as connection:
            row = connection.execute(
                "SELECT vector FROM vectors WHERE node_id = %s AND axis = %s",
                (node_id, axis),
            ).fetchone()
        if row is None:
            raise KeyError((node_id, axis))
        return _parse_vector(row["vector"])

    def create_run(self, problem_id: str) -> str:
        run_id = str(uuid.uuid4())
        with self.connect() as connection:
            connection.execute(
                "INSERT INTO discovery_runs (id, problem_id) VALUES (%s, %s)",
                (run_id, problem_id),
            )
        return run_id

    def update_run_trace(self, run_id: str, trace: dict[str, Any]) -> None:
        with self.connect() as connection:
            connection.execute(
                "UPDATE discovery_runs SET trace_json = %s::jsonb WHERE id = %s",
                (json.dumps(trace, sort_keys=True), run_id),
            )

    def save_hypothesis(
        self,
        *,
        run_id: str,
        problem_id: str,
        analogy_node_id: str,
        title: str,
        bridge: str,
        prediction: str,
        rationale: str,
        status: str,
        critic_score: float,
        failure_reason: str,
        obligations: list[ProofObligation],
    ) -> str:
        hypothesis_id = str(uuid.uuid4())
        with self.connect() as connection:
            connection.execute(
                """
                INSERT INTO hypotheses (
                    id, run_id, problem_id, analogy_node_id, title, bridge,
                    prediction, rationale, status, critic_score, failure_reason
                ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                """,
                (
                    hypothesis_id,
                    run_id,
                    problem_id,
                    analogy_node_id,
                    title,
                    bridge,
                    prediction,
                    rationale,
                    status,
                    critic_score,
                    failure_reason,
                ),
            )
            for index, obligation in enumerate(obligations):
                connection.execute(
                    """
                    INSERT INTO proof_obligations (
                        id, hypothesis_id, position, statement, status,
                        verification_method, notes
                    ) VALUES (%s, %s, %s, %s, %s, %s, %s)
                    """,
                    (
                        str(uuid.uuid4()),
                        hypothesis_id,
                        index,
                        obligation.statement,
                        obligation.status,
                        obligation.verification_method,
                        obligation.notes,
                    ),
                )
        return hypothesis_id

    def list_runs(self) -> list[dict[str, Any]]:
        with self.connect() as connection:
            rows = connection.execute(
                "SELECT id, problem_id, created_at::text AS created_at FROM discovery_runs ORDER BY created_at DESC"
            ).fetchall()
        return [dict(row) for row in rows]

    def get_run(self, run_id: str) -> dict[str, Any]:
        with self.connect() as connection:
            run = connection.execute(
                "SELECT id, problem_id, created_at::text AS created_at, trace_json FROM discovery_runs WHERE id = %s",
                (run_id,),
            ).fetchone()
            if run is None:
                raise KeyError(run_id)
            hypotheses = connection.execute(
                "SELECT * FROM hypotheses WHERE run_id = %s ORDER BY critic_score DESC",
                (run_id,),
            ).fetchall()
            result_hypotheses: list[dict[str, Any]] = []
            for hypothesis in hypotheses:
                obligations = connection.execute(
                    """
                    SELECT statement, status, verification_method, notes
                    FROM proof_obligations
                    WHERE hypothesis_id = %s
                    ORDER BY position
                    """,
                    (hypothesis["id"],),
                ).fetchall()
                item = dict(hypothesis)
                item["proof_obligations"] = [dict(row) for row in obligations]
                result_hypotheses.append(item)

        trace = run["trace_json"]
        if isinstance(trace, str):
            trace = json.loads(trace)
        return {
            "id": run["id"],
            "problem_id": run["problem_id"],
            "created_at": run["created_at"],
            "trace": dict(trace),
            "hypotheses": result_hypotheses,
        }
