from __future__ import annotations

from .models import ScientificNode


SEED_NODES = [
    ScientificNode(
        id="breakthrough:lee-yang",
        kind="breakthrough",
        title="Lee–Yang zeros",
        domain="statistical mechanics",
        summary="Complexify a physical field and use partition-function zeros to constrain real-axis phase behavior.",
        mechanism="local positivity and ferromagnetic correlation structure constrain global analytic zero geometry",
        math_structure="positivity analyticity complex zeros correlation inequalities",
        problem_shape="local to global finite to infinite singularity detection",
        failure_modes="loss of positivity finite-size artifact",
    ),
    ScientificNode(
        id="breakthrough:dirac-linearization",
        kind="breakthrough",
        title="Dirac algebraic linearization",
        domain="relativistic quantum mechanics",
        summary="Enlarge scalar coefficients to a matrix algebra so a quadratic relativistic relation can be linearized.",
        mechanism="enlarge algebra factorize a quadratic constraint obtain linear evolution",
        math_structure="clifford algebra matrices symmetry factorization",
        problem_shape="nonlinear to linear representation enlargement local constraint to global dynamics",
        failure_modes="representation may introduce unphysical branches",
    ),
    ScientificNode(
        id="breakthrough:hubbard-stratonovich",
        kind="breakthrough",
        title="Hubbard–Stratonovich transformation",
        domain="many-body physics",
        summary="Introduce an auxiliary field so an interacting quadratic term becomes conditionally linear.",
        mechanism="add latent degrees of freedom to linearize nonlinear interactions conditionally",
        math_structure="gaussian integral latent variable linearization",
        problem_shape="nonlinear to linear enlarge state space interaction decoupling",
        failure_modes="sign problem auxiliary representation instability",
    ),
    ScientificNode(
        id="breakthrough:renormalization",
        kind="breakthrough",
        title="Renormalization group",
        domain="critical phenomena quantum field theory",
        summary="Repeatedly coarse-grain microscopic degrees of freedom and study flow in theory space.",
        mechanism="discard microscopic information retain relevant directions identify fixed points and universality",
        math_structure="scale invariance fixed points semigroup coarse graining",
        problem_shape="microscopic to macroscopic finite to infinite universality",
        failure_modes="uncontrolled coarse graining no scale separation",
    ),
    ScientificNode(
        id="breakthrough:sturm",
        kind="breakthrough",
        title="Sturm oscillation theory",
        domain="ordinary differential equations spectral theory",
        summary="Use local differential/self-adjoint structure to force global ordering and reality properties of spectra.",
        mechanism="local operator constraints and self-adjointness impose global spectral rigidity",
        math_structure="self-adjointness spectrum oscillation order positivity",
        problem_shape="local to global coefficient structure to spectral location",
        failure_modes="loss of self-adjointness noncompact spectrum",
    ),
    ScientificNode(
        id="breakthrough:herglotz",
        kind="breakthrough",
        title="Herglotz–Nevanlinna representation",
        domain="complex analysis operator theory",
        summary="Analytic maps constrained by half-plane positivity admit a rigid integral representation.",
        mechanism="positivity of an analytic map forces global integral representation and rigidity",
        math_structure="analyticity positivity measures integral representation",
        problem_shape="local to global positivity to analytic rigidity",
        failure_modes="positivity hypothesis too strong boundary regularity",
    ),
    ScientificNode(
        id="breakthrough:path-integral",
        kind="breakthrough",
        title="Path integral",
        domain="quantum mechanics",
        summary="Replace one trajectory by an ensemble over all trajectories weighted by an action.",
        mechanism="lift dynamics from a single path to a weighted ensemble where interference exposes classical stationary structure",
        math_structure="measure action variational principle complex phase",
        problem_shape="single object to ensemble local dynamics to global amplitude",
        failure_modes="measure not rigorous oscillatory integral",
    ),
    ScientificNode(
        id="breakthrough:dimensional-regularization",
        kind="breakthrough",
        title="Dimensional regularization",
        domain="quantum field theory",
        summary="Treat dimension as an analytic parameter to isolate divergences and continue back to the physical dimension.",
        mechanism="embed a singular problem in an analytic parameter family isolate poles then renormalize",
        math_structure="analytic continuation meromorphic functions regularization",
        problem_shape="singular to regular parameter continuation finite to limiting",
        failure_modes="nonuniform limit analytic continuation loses physical solution",
    ),
    ScientificNode(
        id="problem:riemann-hypothesis",
        kind="problem",
        title="Riemann hypothesis",
        domain="analytic number theory",
        summary="Explain why all nontrivial zeros of the zeta function satisfy a rigid codimension-one location constraint.",
        mechanism="derive global zero-location rigidity from arithmetic or coefficient-level structure without assuming the zero locations",
        math_structure="analyticity multiplicativity symmetry zeros positivity spectrum",
        problem_shape="local to global coefficient structure to zero location finite approximants to entire function",
        failure_modes="circular reformulation loss of positivity universal representation nonuniform limit",
    ),
    ScientificNode(
        id="problem:navier-stokes",
        kind="problem",
        title="3D Navier–Stokes regularity",
        domain="partial differential equations fluid mechanics",
        summary="Determine whether smooth finite-energy initial data can develop a finite-time singularity in three dimensions.",
        mechanism="control concentration in a nonlinear dissipative evolution strongly enough to continue solutions globally",
        math_structure="energy dissipation nonlinear PDE scaling compactness regularity",
        problem_shape="local existence to global continuation finite to infinite concentration obstruction",
        failure_modes="nonuniform limit missing critical norm bound circular continuation estimate",
    ),
    ScientificNode(
        id="problem:origin-of-life",
        kind="problem",
        title="Origin of self-sustaining life-like chemistry",
        domain="origin of life chemical reaction networks",
        summary="Identify general conditions under which externally driven chemistry becomes internally self-sustaining and heritable.",
        mechanism="derive persistent causal closure from local reaction rules and stochastic trajectories",
        math_structure="networks stochastic processes autocatalysis nonequilibrium dynamics",
        problem_shape="local to global microscopic to macroscopic single trajectory to ensemble emergence",
        failure_modes="finite-size artifact arbitrary order parameter uncontrolled coarse graining",
    ),
    ScientificNode(
        id="problem:grokking",
        kind="problem",
        title="Grokking and abrupt generalization",
        domain="machine learning",
        summary="Explain and predict delayed abrupt generalization during neural-network training.",
        mechanism="identify a robust latent structural transition before observable generalization occurs",
        math_structure="optimization dynamics representation geometry stochastic trajectories",
        problem_shape="microscopic to macroscopic trajectory to phase-like transition prediction",
        failure_modes="finite-size artifact metric threshold random-label false positive",
    ),
]
