from __future__ import annotations

from .models import ScientificNode


SEED_NODES = [
    ScientificNode(
        id="breakthrough:lee-yang",
        kind="breakthrough",
        title="Lee–Yang zeros",
        domain="statistical mechanics",
        summary="Complexify a physical field and use partition-function zeros to constrain real-axis phase behavior.",
        mechanism="local positivity and ferromagnetic correlation structure constrain global analytic zero geometry",
        math_structure="positivity analyticity complex zeros correlation inequalities",
        problem_shape="local to global finite to infinite singularity detection",
        failure_modes="loss of positivity finite-size artifact",
    ),
    ScientificNode(
        id="breakthrough:dirac-linearization",
        kind="breakthrough",
        title="Dirac algebraic linearization",
        domain="relativistic quantum mechanics",
        summary="Enlarge scalar coefficients to a matrix algebra so a quadratic relativistic relation can be linearized.",
        mechanism="enlarge algebra factorize a quadratic constraint obtain linear evolution",
        math_structure="clifford algebra matrices symmetry factorization",
        problem_shape="nonlinear to linear representation enlargement local constraint to global dynamics",
        failure_modes="representation may introduce unphysical branches",
    ),
    ScientificNode(
        id="breakthrough:hubbard-stratonovich",
        kind="breakthrough",
        title="Hubbard–Stratonovich transformation",
        domain="many-body physics",
        summary="Introduce an auxiliary field so an interacting quadratic term becomes conditionally linear.",
        mechanism="add latent degrees of freedom to linearize nonlinear interactions conditionally",
        math_structure="gaussian integral latent variable linearization",
        problem_shape="nonlinear to linear enlarge state space interaction decoupling",
        failure_modes="sign problem auxiliary representation instability",
    ),
    ScientificNode(
        id="breakthrough:renormalization",
        kind="breakthrough",
        title="Renormalization group",
        domain="critical phenomena quantum field theory",
        summary="Repeatedly coarse-grain microscopic degrees of freedom and study flow in theory space.",
        mechanism="discard microscopic information retain relevant directions identify fixed points and universality",
        math_structure="scale invariance fixed points semigroup coarse graining",
        problem_shape="microscopic to macroscopic finite to infinite universality",
        failure_modes="uncontrolled coarse graining no scale separation",
    ),
    ScientificNode(
        id="breakthrough:sturm",
        kind="breakthrough",
        title="Sturm oscillation theory",
        domain="ordinary differential equations spectral theory",
        summary="Use local differential/self-adjoint structure to force global ordering and reality properties of spectra.",
        mechanism="local operator constraints and self-adjointness impose global spectral rigidity",
        math_structure="self-adjointness spectrum oscillation order positivity",
        problem_shape="local to global coefficient structure to spectral location",
        failure_modes="loss of self-adjointness noncompact spectrum",
    ),
    ScientificNode(
        id="breakthrough:herglotz",
        kind="breakthrough",
        title="Herglotz–Nevanlinna representation",
        domain="complex analysis operator theory",
        summary="Analytic maps constrained by half-plane positivity admit a rigid integral representation.",
        mechanism="positivity of an analytic map forces global integral representation and rigidity",
        math_structure="analyticity positivity measures integral representation",
        problem_shape="local to global positivity to analytic rigidity",
        failure_modes="positivity hypothesis too strong boundary regularity",
    ),
    ScientificNode(
        id="breakthrough:path-integral",
        kind="breakthrough",
        title="Path integral",
        domain="quantum mechanics",
        summary="Replace one trajectory by an ensemble over all trajectories weighted by an action.",
        mechanism="lift dynamics from a single path to a weighted ensemble where interference exposes classical stationary structure",
        math_structure="measure action variational principle complex phase",
        problem_shape="single object to ensemble local dynamics to global amplitude",
        failure_modes="measure not rigorous oscillatory integral",
    ),
    ScientificNode(
        id="breakthrough:dimensional-regularization",
        kind="breakthrough",
        title="Dimensional regularization",
        domain="quantum field theory",
        summary="Treat dimension as an analytic parameter to isolate divergences and continue back to the physical dimension.",
        mechanism="embed a singular problem in an analytic parameter family isolate poles then renormalize",
        math_structure="analytic continuation meromorphic functions regularization",
        problem_shape="singular to regular parameter continuation finite to limiting",
        failure_modes="nonuniform limit analytic continuation loses physical solution",
    ),
    ScientificNode(
        id="problem:riemann-hypothesis",
        kind="problem",
        title="Riemann hypothesis",
        domain="analytic number theory",
        summary="Explain why all nontrivial zeros of the zeta function satisfy a rigid codimension-one location constraint.",
        mechanism="derive global zero-location rigidity from arithmetic or coefficient-level structure without assuming the zero locations",
        math_structure="analyticity multiplicativity symmetry zeros positivity spectrum",
        problem_shape="local to global coefficient structure to zero location finite approximants to entire function",
        failure_modes="circular reformulation loss of positivity universal representation nonuniform limit",
    ),
    ScientificNode(
        id="problem:navier-stokes",
        kind="problem",
        title="3D Navier–Stokes regularity",
        domain="partial differential equations fluid mechanics",
        summary="Determine whether smooth finite-energy initial data can develop a finite-time singularity in three dimensions.",
        mechanism="control concentration in a nonlinear dissipative evolution strongly enough to continue solutions globally",
        math_structure="energy dissipation nonlinear PDE scaling compactness regularity",
        problem_shape="local existence to global continuation finite to infinite concentration obstruction",
        failure_modes="nonuniform limit missing critical norm bound circular continuation estimate",
    ),
    ScientificNode(
        id="problem:origin-of-life",
        kind="problem",
        title="Origin of self-sustaining life-like chemistry",
        domain="origin of life chemical reaction networks",
        summary="Identify general conditions under which externally driven chemistry becomes internally self-sustaining and heritable.",
        mechanism="derive persistent causal closure from local reaction rules and stochastic trajectories",
        math_structure="networks stochastic processes autocatalysis nonequilibrium dynamics",
        problem_shape="local to global microscopic to macroscopic single trajectory to ensemble emergence",
        failure_modes="finite-size artifact arbitrary order parameter uncontrolled coarse graining",
    ),
    ScientificNode(
        id="problem:grokking",
        kind="problem",
        title="Grokking and abrupt generalization",
        domain="machine learning",
        summary="Explain and predict delayed abrupt generalization during neural-network training.",
        mechanism="identify a robust latent structural transition before observable generalization occurs",
        math_structure="optimization dynamics representation geometry stochastic trajectories",
        problem_shape="microscopic to macroscopic trajectory to phase-like transition prediction",
        failure_modes="finite-size artifact metric threshold random-label false positive",
    ),
    ScientificNode(
        id="problem:frankl-union-closed",
        kind="problem",
        title="Frankl union-closed sets conjecture",
        domain="combinatorics",
        summary="Prove every nontrivial finite union-closed family has an element in at least half its members.",
        mechanism="show closure operation alone forces concentration of element frequency",
        math_structure="set families closure operators frequency counting extremal combinatorics",
        problem_shape="local rule to global guarantee existence of abundant object",
        failure_modes="frequency-vector reductions without exploitable structure",
    ),
    ScientificNode(
        id="problem:glass-transition",
        kind="problem",
        title="Glass transition thermodynamic or kinetic",
        domain="condensed matter statistical mechanics",
        summary="Determine whether the structural glass transition hides a genuine thermodynamic singularity or is only kinetic slowdown.",
        mechanism="separate true collective transition from smooth finite-time dynamical arrest",
        math_structure="energy landscapes metastability mode coupling random first order transition",
        problem_shape="genuine singularity versus finite-time artifact",
        failure_modes="static signatures mimicked by kinetic controls",
    ),
    ScientificNode(
        id="problem:planted-clique-hardness",
        kind="problem",
        title="Planted clique average-case threshold",
        domain="theoretical computer science average-case complexity",
        summary="Locate the computational threshold for detecting planted cliques between log n and sqrt n.",
        mechanism="separate information-theoretic possibility from algorithmic reachability",
        math_structure="random graphs spectral methods semidefinite programming sum-of-squares lower bounds",
        problem_shape="threshold location proving absence of algorithms",
        failure_modes="lower bounds limited to narrow classes circular reductions",
    ),
    ScientificNode(
        id="problem:edit-distance-barrier",
        kind="problem",
        title="Edit distance quadratic time barrier",
        domain="algorithms stringology",
        summary="Decide whether edit distance admits a strongly subquadratic algorithm, equivalent to refuting SETH.",
        mechanism="find exploitable string structure or prove conditional lower bound via fine-grained reduction",
        math_structure="dynamic programming fine-grained complexity seth reductions orthogonal vectors",
        problem_shape="prove impossibility or find hidden structure enabling speedup",
        failure_modes="quadratic information content of alignment tables blocks all known techniques",
    ),
    ScientificNode(
        id="problem:turbulence-intermittency",
        kind="problem",
        title="Turbulence intermittency anomalies",
        domain="fluid mechanics turbulence",
        summary="Derive anomalous scaling exponents of velocity statistics from governing dynamics instead of fitting multifractal phenomenology.",
        mechanism="account for extreme events dominating high-order moments from first principles",
        math_structure="multifractal formalism structure functions scale invariance breakdown large deviations",
        problem_shape="fitting replaced by derivation of spectrum",
        failure_modes="descriptive cascade models closures miss intermittency",
    ),
    ScientificNode(
        id="problem:enzyme-catalysis-origin",
        kind="problem",
        title="Physical origin of enzyme catalytic power",
        domain="biochemistry enzymology",
        summary="Explain and predict enormous enzymatic rate accelerations from structure with separable physical contributions.",
        mechanism="decompose rate acceleration into contributions that resist clean separation",
        math_structure="transition state theory free energy surfaces reorganization protein dynamics",
        problem_shape="attribution problem structure-to-rate prediction",
        failure_modes="arbitrary partitioning of free energy surface",
    ),
    ScientificNode(
        id="problem:evolution-of-sex",
        kind="problem",
        title="Maintenance of sex and recombination",
        domain="evolutionary biology population genetics",
        summary="Identify which advantage systematically overcomes the twofold cost of sex across natural populations.",
        mechanism="attribute recombination benefit under fluctuating selection and mutation load",
        math_structure="population genetics linkage disequilibrium selection epistasis mutation load",
        problem_shape="cost-benefit attribution across environments",
        failure_modes="every proposed benefit regime-dependent no universal winner demonstrated",
    ),
    ScientificNode(
        id="problem:anesthesia-mechanism",
        kind="problem",
        title="Mechanism of general anesthesia",
        domain="neuroscience anesthesiology",
        summary="Explain how chemically diverse agents reversibly abolish consciousness through shared circuit mechanisms.",
        mechanism="identify invariant circuit signature behind many-to-one convergence of molecular targets",
        math_structure="neural circuits excitation inhibition balance network dynamics arousal systems",
        problem_shape="many-to-one convergence identify shared endpoint mechanism",
        failure_modes="molecular targets do not predict consciousness loss correlates without mechanism",
    ),
    ScientificNode(
        id="problem:auction-design-robustness",
        kind="problem",
        title="Robust prior-free combinatorial auction design",
        domain="market design algorithmic game theory",
        summary="Design combinatorial auctions with good guarantees without distributional knowledge and with tractable expressive bids.",
        mechanism="achieve guarantees against unknown environments while keeping allocation computable",
        math_structure="mechanism design incentive compatibility approximation algorithms worst-case analysis learning theory",
        problem_shape="unknown environment made harmless by design expressiveness versus tractability",
        failure_modes="distributional assumptions sneak back via benchmarks welfare-revenue tradeoffs unresolved",
    ),
    ScientificNode(
        id="problem:loop-invariant-inference",
        kind="problem",
        title="Automated loop invariant inference",
        domain="programming languages formal verification",
        summary="Automatically synthesize inductive invariants for realistic loops including non-obvious nonlinear ones.",
        mechanism="discover inductive assertions without template guessing at scale",
        math_structure="fixed points inductive assertions constraint solving abstract interpretation",
        problem_shape="search space explosion template selection as hidden bottleneck",
        failure_modes="linear-arithemtic bias fails on nonlinear disjunctive invariants",
    ),
    ScientificNode(
        id="breakthrough:galois",
        kind="breakthrough",
        title="Galois root symmetry",
        domain="algebra theory of equations",
        summary="Decide solvability of equations by the permutation group of roots instead of searching for formulas; quintic unsolvability follows from S5 not being solvable.",
        mechanism="shift object of study to invariant structure any solution must respect prove obstruction",
        math_structure="group theory field extensions galois correspondence solvable groups",
        problem_shape="formula search to structural obstruction existence to nonexistence",
        failure_modes="no explicit construction computability of resolvents",
    ),
    ScientificNode(
        id="breakthrough:cantor-diagonalization",
        kind="breakthrough",
        title="Cantor diagonalization",
        domain="set theory foundations",
        summary="Treat completed infinities as objects; refute any universal list by a witness defined to differ from every entry.",
        mechanism="define witness by opposition differ from nth candidate at position n list never complete",
        math_structure="bijection cardinality diagonal argument self-reference negation",
        problem_shape="enumeration to non-enumerability universal claim refuted by single adversarial witness",
        failure_modes="naive comprehension paradoxes needs axiomatic framework",
    ),
    ScientificNode(
        id="breakthrough:boltzmann-statistical",
        kind="breakthrough",
        title="Boltzmann microstate counting",
        domain="thermodynamics kinetic theory",
        summary="Derive macroscopic irreversibility and entropy from counting microscopic configurations, S proportional to log W.",
        mechanism="reframe deterministic question as ensemble counting typicality replaces prediction",
        math_structure="combinatorics logarithmic additivity law of large numbers ensembles",
        problem_shape="microscopic to macroscopic reversible dynamics to irreversible law exact prediction to statistical explanation",
        failure_modes="reversibility objections recurrence objections ergodic assumptions",
    ),
    ScientificNode(
        id="breakthrough:mendel",
        kind="breakthrough",
        title="Mendel particulate inheritance",
        domain="genetics heredity",
        summary="Discretize the hidden hereditary substrate and predict observable integer ratios before knowing its physical carrier.",
        mechanism="discretize hidden variable derive observable ratios as combinatorics test by counting",
        math_structure="discrete factors segregation ratios combinatorial probability",
        problem_shape="continuous blending to discrete units hidden variable inferred from ratio statistics",
        failure_modes="continuous traits linkage carrier unknown",
    ),
    ScientificNode(
        id="breakthrough:noether",
        kind="breakthrough",
        title="Noether symmetry conservation correspondence",
        domain="theoretical physics variational calculus",
        summary="Every differentiable symmetry of the action yields a conserved current; conservation laws are shadows of symmetries.",
        mechanism="vary generating functional under continuous symmetry boundary term is conserved current",
        math_structure="variational principle lie groups currents conservation laws",
        problem_shape="symmetry to law independent facts unified as consequences of invariance",
        failure_modes="needs variational formulation differentiable symmetries quantum anomalies",
    ),
    ScientificNode(
        id="breakthrough:godel-arithmetization",
        kind="breakthrough",
        title="Goedel arithmetization and self-reference",
        domain="mathematical logic foundations",
        summary="Encode metamathematics inside arithmetic via Goedel numbering; construct a sentence asserting its own unprovability, yielding incompleteness.",
        mechanism="collapse meta level into object level by encoding self reference does the work",
        math_structure="goedel numbering recursive functions diagonal lemma incompleteness",
        problem_shape="meta-level to object-level limitation proofs become internal constructions",
        failure_modes="requires effective axiomatization sufficient expressiveness consistency strength caveats",
    ),
    ScientificNode(
        id="breakthrough:cohen-forcing",
        kind="breakthrough",
        title="Cohen forcing",
        domain="set theory foundations",
        summary="Prove independence by constructing enlarged models adjoined with generic sets controlled through dense-set approximation.",
        mechanism="build larger universe control truth via finite approximations meeting dense sets answer becomes design parameter",
        math_structure="partial orders generic filters forcing relation model construction",
        problem_shape="prove non-provability by construction finite control of infinite objects",
        failure_modes="cardinal preservation side conditions forcing bookkeeping",
    ),
    ScientificNode(
        id="breakthrough:taylor-wiles",
        kind="breakthrough",
        title="Taylor-Wiles patching and R=T counting",
        domain="number theory arithmetic geometry",
        summary="Establish deformation-ring/Hecke-algebra equality numerically by patching infinitely many auxiliary modular forms and matching Selmer-group counts.",
        mechanism="count deformations two ways auxiliary infinite family makes both sides countable in same units size equality forces isomorphism",
        math_structure="galois deformations selmer groups commutative algebra length counting patching systems",
        problem_shape="infinite family compressed into single object identity proved by numerical invariant",
        failure_modes="smoothness assumptions refined systems needed for non-minimal cases",
    ),
    ScientificNode(
        id="breakthrough:perelman-w-entropy",
        kind="breakthrough",
        title="Perelman W-entropy and Ricci flow surgery",
        domain="geometric analysis topology",
        summary="Classify 3-manifolds by Ricci flow with surgery controlled by monotone weighted entropy preventing collapse.",
        mechanism="monotone thermodynamic functional converts local smoothing into global classification excise singular regions restart",
        math_structure="gradient flow ricci flow entropy monotonicity optimal transportation surgery",
        problem_shape="topology solved as heat-flow dynamics singularity control by quantitative monotonicity",
        failure_modes="surgery parameter tuning noncompact versions delicate",
    ),
    ScientificNode(
        id="breakthrough:cole-hopf",
        kind="breakthrough",
        title="Cole-Hopf transformation",
        domain="partial differential equations fluid mechanics",
        summary="Remove Burgers quadratic nonlinearity exactly via u = -2 nu (log phi)_x mapping to the linear heat equation.",
        mechanism="exponential change of dependent variable converts quadratic advection into logarithmic derivative of linearly diffusing field",
        math_structure="nonlinear-to-linear substitution logarithmic derivative heat equation maximum principle",
        problem_shape="nonlinear to linear shocks as zeros of positive quantity",
        failure_modes="only special nonlinearities no navier-stokes analogue",
    ),
    ScientificNode(
        id="breakthrough:wick-rotation",
        kind="breakthrough",
        title="Wick rotation",
        domain="quantum field theory mathematical physics",
        summary="Compute oscillatory Lorentzian path integrals by rotating time to the imaginary axis into convergent Euclidean integrals, then continue back.",
        mechanism="rotate parameter into complex plane converting oscillation into damping recover answers by analytic continuation",
        math_structure="analytic continuation contour rotation reflection positivity euclidean field theory",
        problem_shape="divergent oscillatory to convergent real time to imaginary time",
        failure_modes="return continuation ill-posed scattering resists reconstruction",
    ),
    ScientificNode(
        id="breakthrough:kohn-sham",
        kind="breakthrough",
        title="Kohn-Sham fictitious system",
        domain="condensed matter quantum chemistry",
        summary="Replace interacting electrons with a fictitious noninteracting system matching the exact density, absorbing all complexity into one exchange-correlation functional.",
        mechanism="density as fundamental variable surrogate solvable system mirrors true one observables concentrate error into single improvable functional",
        math_structure="variational principle hohenberg-kohn theorem self-consistent field fixed point iteration",
        problem_shape="many-body to effective single-particle exactness relocated into approximation",
        failure_modes="unknown exact functional self-interaction derivative discontinuities fictitious orbitals not physical",
    ),
    ScientificNode(
        id="breakthrough:bethe-ansatz",
        kind="breakthrough",
        title="Bethe ansatz",
        domain="integrable systems 1d quantum many-body",
        summary="Find exact eigenstates by postulating factorized two-body elastic scattering; consistency of the assumed form generates the full spectrum.",
        mechanism="ansatz first postulate restricted solution shape consistency around permutations yields exact equations",
        math_structure="factorized scattering yang-baxter equation bethe equations integrability",
        problem_shape="guess-and-verify many-body reduced to two-body data plus consistency",
        failure_modes="1d integrable models only higher-dimensional diffraction",
    ),
    ScientificNode(
        id="breakthrough:shannon-entropy",
        kind="breakthrough",
        title="Shannon statistical information",
        domain="information theory communication engineering",
        summary="Model communication purely statistically: entropy measures information, capacity bounds transmission, meaning deliberately discarded.",
        mechanism="discard meaning retain distribution limits become variational quantities asymptotic equipartition",
        math_structure="entropy typical sequences mutual information channel capacity random coding",
        problem_shape="semantic to syntactic engineering craft replaced by existence theorems with achievable bounds",
        failure_modes="semantics out of scope finite-blocklength gaps",
    ),
    ScientificNode(
        id="breakthrough:black-scholes",
        kind="breakthrough",
        title="Black-Scholes-Merton replication pricing",
        domain="mathematical finance stochastic calculus",
        summary="Price derivatives as the cost of a self-financing dynamic replicating portfolio so risk premia and preferences cancel exactly.",
        mechanism="continuous delta hedging removes risk locally change of measure absorbs preferences price by construction not forecast",
        math_structure="ito calculus martingales girsanov theorem parabolic pde self-financing portfolios",
        problem_shape="unknown preference made irrelevant forecasting replaced by hedging",
        failure_modes="continuous trading assumption volatility knowledge crashes break replication",
    ),
    ScientificNode(
        id="breakthrough:prion",
        kind="breakthrough",
        title="Prion protein-only inheritance",
        domain="molecular biology neurodegeneration",
        summary="Infectious agents can be pure protein conformations propagating by templated conversion, without nucleic acid genomes.",
        mechanism="separate informational process from assumed material carrier templated conformational conversion autocatalysis by nucleated polymerization",
        math_structure="autocatalysis nucleation polymerization kinetics conformational templating",
        problem_shape="substrate-free inheritance central dogma violation resolved by redefining carrier",
        failure_modes="strain phenomena species barrier kinetics initially suggested nucleic acid",
    ),
    ScientificNode(
        id="problem:battery-interface-degradation",
        kind="problem",
        title="Predicting battery interface degradation from first principles",
        domain="electrochemistry/materials science",
        summary="Lithium-ion and next-generation batteries fail through evolving interphases (SEI, cathode-electrolyte interfaces) whose chemistry and mechanics change with every cycle. No predictive model connects...",
        mechanism="interphase growth coupled to transport, mechanics, and side-reaction networks resists closed-form modeling",
        math_structure="reaction diffusion stochastic interfaces coupled multiscale models aging laws",
        problem_shape="atomistic to device-lifetime extrapolation; cross-chemistry generality",
        failure_modes="empirical aging laws do not transfer across chemistries; atomistic simulations too slow for cycles",
    ),
    ScientificNode(
        id="problem:cloud-feedback-sensitivity",
        kind="problem",
        title="Cloud feedback: the dominant uncertainty in climate sensitivity",
        domain="climate physics/atmospheric science",
        summary="How low marine clouds and tropical high clouds respond to warming remains the largest single source of spread in equilibrium climate sensitivity across models. Decades of observations and...",
        mechanism="competing positive and negative cloud feedbacks across regimes; subgrid turbulence-convection coupling",
        math_structure="radiative convective equilibrium large eddy simulation mixed layer budgets emergent constraint statistics",
        problem_shape="subgrid process to global sensitivity attribution among competing mechanisms",
        failure_modes="global models parameterize clouds; LES covers limited domains and timescales",
    ),
    ScientificNode(
        id="problem:fusion-edge-turbulence-control",
        kind="problem",
        title="Controlling edge turbulence and heat loads in fusion plasmas",
        domain="plasma physics/energy",
        summary="Tokamak performance is limited by edge-localized modes and boundary turbulence that can dump destructive heat fluxes onto plasma-facing walls. Predictive control of the pedestal-edge region across...",
        mechanism="pressure-gradient-driven instabilities interacting with shear flows and radiation",
        math_structure="gyrokinetics magnetohydrodynamics bifurcation control real-time estimation",
        problem_shape="microscale turbulence to macroscopic stability margins; prediction to actuation",
        failure_modes="reduced models tuned per device; first-principles simulation far slower than real time",
    ),
    ScientificNode(
        id="problem:predictive-catalyst-design",
        kind="problem",
        title="First-principles predictive design of earth-abundant electrocatalysts",
        domain="chemistry/electrocatalysis/green energy",
        summary="Designing catalysts for hydrogen evolution, CO2 reduction, or nitrogen fixation from computed properties alone fails reliably: activity descriptors (e.g., scaling relations) cap selectivity, and...",
        mechanism="descriptor-based screening hits scaling relation ceilings; operando surfaces differ from modeled ones",
        math_structure="dft scaling relations microkinetic models genetic algorithm search operando spectroscopy",
        problem_shape="static property to dynamic working-state prediction; screening to synthesis",
        failure_modes="scaling relations force tradeoffs; reconstruction dynamics rarely captured",
    ),
    ScientificNode(
        id="problem:epidemic-trajectory-forecasting",
        kind="problem",
        title="Skillful mid-term epidemic trajectory forecasting",
        domain="epidemiology/public health",
        summary="Short-horizon epidemic forecasts have modest skill, but predicting trajectories beyond 4-8 weeks (where decisions matter most) has largely failed: behavior change, waning immunity, variant emergence,...",
        mechanism="human behavior couples to incidence; pathogen evolution shifts the system mid-forecast",
        math_structure="branching processes renewal equations mechanistic compartmental models ensemble probabilistic forecasting",
        problem_shape="nonstationary coupled system; decision-relevant horizons",
        failure_modes="models fit past waves but miss regime changes; data delays corrupt calibration",
    ),
    ScientificNode(
        id="problem:crop-photosynthesis-limit",
        kind="problem",
        title="Raising crop photosynthetic efficiency beyond natural limits",
        domain="plant science/agriculture",
        summary="C3 photosynthesis converts well under 5% of available solar energy into biomass, with known engineered inefficiencies (photorespiration, slow recovery from shade, insufficient Rubisco speed). Which...",
        mechanism="leaf-scale improvements wash out through canopy, source-sink, and stress interactions",
        math_structure="canopy radiation transfer enzyme kinetics whole-plant allocation quantitative genetics",
        problem_shape="molecular mechanism to agronomic trait; controlled environment to field",
        failure_modes="leaf-level gains historically fail to propagate to yield; genotype-environment management interactions dominate",
    ),
    ScientificNode(
        id="problem:earthquake-rupture-forecast",
        kind="problem",
        title="Physics-based earthquake rupture and aftershock forecasting",
        domain="seismology/geophysics",
        summary="Earthquake prediction beyond statistical recurrence catalogs remains elusive: fault stress states are unobservable directly, rupture initiation physics spans nanometers to kilometers, and proposed...",
        mechanism="stress accumulation and heterogeneous friction produce cascading ruptures sensitive to fine detail",
        math_structure="rate-and-state friction elastodynamics point process statistics Coulomb stress transfer",
        problem_shape="unobservable initial condition to probabilistic forecast; scale separation",
        failure_modes="catalogs are statistical not physical; candidate precursors fail out-of-sample tests",
    ),
    ScientificNode(
        id="problem:antibiotic-resistance-prediction",
        kind="problem",
        title="Predicting antibiotic resistance emergence before it spreads",
        domain="microbiology/evolutionary medicine",
        summary="Which mutations, gene acquisitions, and backgrounds will confer clinically relevant resistance - and in which species and settings they will emerge - cannot be predicted reliably. Surveillance...",
        mechanism="genotype-phenotype maps for resistance are context-dependent; fitness costs and compensation vary by environment",
        math_structure="fitness landscapes epistasis population genetics phylogenetic forecasting machine learning on sequences",
        problem_shape="forecast of contingent evolution; laboratory fitness to clinical success",
        failure_modes="predictive models trained on known paths generalize poorly to novel mutations",
    ),
    ScientificNode(
        id="problem:materials-fatigue-microstructure",
        kind="problem",
        title="Microstructure-to-lifetime prediction for structural materials fatigue",
        domain="mechanical engineering/materials science",
        summary="Fatigue life of metals and composites varies by orders of magnitude due to microstructural detail (inclusions, grain orientation, defects) that scatter standard S-N curves. Predicting remaining life...",
        mechanism="crack initiation at extreme microstructural features dominates; extremes resist continuum modeling",
        math_structure="fracture mechanics crystal plasticity extreme value statistics defect distributions",
        problem_shape="extreme-event-dominated lifetime; specimen statistics to individual part",
        failure_modes="models calibrated on averages miss tail events that determine failure",
    ),
    ScientificNode(
        id="problem:wildfire-spread-prediction",
        kind="problem",
        title="Reliable wildfire spread prediction in complex terrain under extreme weather",
        domain="fire science/hazard prediction",
        summary="Fire spread models perform adequately in mild conditions but break down exactly when stakes are highest: wind-fire coupling, spotting, dry thunderstorms, and fuel heterogeneity make extreme-fire...",
        mechanism="fire-atmosphere coupling creates self-organized extreme behavior; fuels data too coarse",
        math_structure="coupled fire atmosphere models cellular automata emulators probabilistic ensembles remote sensing assimilation",
        problem_shape="tail-risk prediction; coupling between fluid dynamics and combustion at landscape scale",
        failure_modes="models validated on ordinary fires; extreme cases are rare, fast, and data-poor",
    ),
    ScientificNode(
        id="problem:erdos-straus",
        kind="problem",
        title="Erdos-Straus conjecture: 4/n as three unit fractions",
        domain="number theory/Diophantine equations",
        summary="For every integer n >= 2, the equation 4/n = 1/x + 1/y + 1/z has a solution in positive integers x <= y <= z. Verified computationally far beyond 10^14 via divisor-enumeration methods, but no proof...",
        mechanism="divisor structure of quadratic polynomials in n parametrizes all solutions",
        math_structure="egyptian fractions divisor counting congruence classes density arguments",
        problem_shape="universal existence statement reduced to checking finitely many residue patterns",
        failure_modes="proofs cover density-1 subsets; exceptional residue classes resist all known methods",
    ),
    ScientificNode(
        id="problem:lonely-runner",
        kind="problem",
        title="Lonely Runner Conjecture",
        domain="combinatorics/dynamical systems",
        summary="Given k runners with distinct constant speeds on a unit-length circular track, each runner is at some time at distance at least 1/(k+1) from every other runner ('lonely'). Proved only for small k (k...",
        mechanism="view of view graph chromatic number bounds; torus orbit equidistribution",
        math_structure="view obstructions chromatic numbers diophantine approximation torus flows",
        problem_shape="existential over continuous time reduced to finite speed-ratio structure",
        failure_modes="chromatic lower bounds insufficient beyond small k; equidistribution gives no uniform rate",
    ),
    ScientificNode(
        id="problem:singmaster",
        kind="problem",
        title="Singmaster's conjecture: bounded multiplicity in Pascal's triangle",
        domain="combinatorics/number theory",
        summary="There is a finite upper bound on how many times any integer > 1 can appear in Pascal's triangle. The maximum known multiplicity is 6 (entry 3003); extensive searches found nothing above it, but no...",
        mechanism="equalities c(n,k)=c(m,l) define algebraic curves whose integral points are rare",
        math_structure="binomial coefficients diophantine equations algebraic curves effective bounds",
        problem_shape="global bound from point-counting on curves",
        failure_modes="effective bounds from Faltings-type results are astronomically weak",
    ),
    ScientificNode(
        id="problem:lehmer-totient",
        kind="problem",
        title="Lehmer's totient problem",
        domain="number theory",
        summary="No composite n satisfies phi(n) | (n-1). If such n exists it must be odd, squarefree, and have at least 15 distinct prime factors (bounds pushed by successive searches); none...",
        mechanism="phi divisibility forces extremely constrained multiplicative structure",
        math_structure="totients carmichael-like structures sieving modular arithmetic",
        problem_shape="nonexistence via structural constraints plus finite search",
        failure_modes="each added factor multiplies search space; constraints weaken as factor count grows",
    ),
    ScientificNode(
        id="problem:giuga",
        kind="problem",
        title="Giuga's conjecture",
        domain="number theory",
        summary="A composite n with sum_{p|n} 1/p - prod_{p|n} 1/p being an integer would be a counterexample to Giuga's conjecture that no such n exists. Any counterexample must be a Carmichael number with p | (n/p...",
        mechanism="condition couples primality-like behavior with prime-factor reciprocals",
        math_structure="carmichael numbers agoh-giuga congruences harmonic sums sieving",
        problem_shape="nonexistence via rare structured intersection of two sparse classes",
        failure_modes="candidate class unbounded; searches rely on Carmichael enumeration growth",
    ),
    ScientificNode(
        id="problem:graceful-tree",
        kind="problem",
        title="Graceful Tree Conjecture (Ringel-Kotzig)",
        domain="graph theory/combinatorics",
        summary="Every tree with m edges admits a graceful labeling: injective vertex labels from {0,...,m} such that edge labels |difference| are all distinct (1..m). Open since 1967 despite intense effort; verified...",
        mechanism="labeling constraints propagate along tree structure; constructive induction resists generalization",
        math_structure="graph labelings combinatorial search parity arguments bipartite structure",
        problem_shape="universal construction statement; induction over tree decompositions fails globally",
        failure_modes="known constructions cover restricted families (caterpillars, symmetrical trees); general trees resist",
    ),
]
